# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RVRSpheroServices.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SensorData_pb2 as SensorData__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='RVRSpheroServices.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17RVRSpheroServices.proto\x1a\x10SensorData.proto2G\n\x10RVRSpheroService\x12\x33\n\x10UpdateSensorData\x12\x12.SensorDataRequest\x1a\x0b.SensorDatab\x06proto3'
  ,
  dependencies=[SensorData__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_RVRSPHEROSERVICE = _descriptor.ServiceDescriptor(
  name='RVRSpheroService',
  full_name='RVRSpheroService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=45,
  serialized_end=116,
  methods=[
  _descriptor.MethodDescriptor(
    name='UpdateSensorData',
    full_name='RVRSpheroService.UpdateSensorData',
    index=0,
    containing_service=None,
    input_type=SensorData__pb2._SENSORDATAREQUEST,
    output_type=SensorData__pb2._SENSORDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RVRSPHEROSERVICE)

DESCRIPTOR.services_by_name['RVRSpheroService'] = _RVRSPHEROSERVICE

# @@protoc_insertion_point(module_scope)
