# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SensorData.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Accelerometer_pb2 as Accelerometer__pb2
import AmbientLight_pb2 as AmbientLight__pb2
import ColorSensor_pb2 as ColorSensor__pb2
import CoreTime_pb2 as CoreTime__pb2
import Gyroscope_pb2 as Gyroscope__pb2
import IMU_pb2 as IMU__pb2
import Locator_pb2 as Locator__pb2
import Quaternion_pb2 as Quaternion__pb2
import Speed_pb2 as Speed__pb2
import Velocity_pb2 as Velocity__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SensorData.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10SensorData.proto\x1a\x13\x41\x63\x63\x65lerometer.proto\x1a\x12\x41mbientLight.proto\x1a\x11\x43olorSensor.proto\x1a\x0e\x43oreTime.proto\x1a\x0fGyroscope.proto\x1a\tIMU.proto\x1a\rLocator.proto\x1a\x10Quaternion.proto\x1a\x0bSpeed.proto\x1a\x0eVelocity.proto\"E\n\x11SensorDataRequest\x12\x18\n\x10sensorFlagLength\x18\x01 \x01(\r\x12\x16\n\nsensorFlag\x18\x02 \x03(\x08\x42\x02\x10\x01\"\xbd\x02\n\nSensorData\x12%\n\raccelerometer\x18\x01 \x01(\x0b\x32\x0e.Accelerometer\x12$\n\rambient_light\x18\x02 \x01(\x0b\x32\r.AmbientLight\x12\"\n\x0c\x63olor_sensor\x18\x03 \x01(\x0b\x32\x0c.ColorSensor\x12\x1c\n\tcore_time\x18\x04 \x01(\x0b\x32\t.CoreTime\x12\x1d\n\tgyroscope\x18\x05 \x01(\x0b\x32\n.Gyroscope\x12\x11\n\x03imu\x18\x06 \x01(\x0b\x32\x04.IMU\x12\x19\n\x07locator\x18\x07 \x01(\x0b\x32\x08.Locator\x12\x1f\n\nquaternion\x18\x08 \x01(\x0b\x32\x0b.Quaternion\x12\x15\n\x05speed\x18\t \x01(\x0b\x32\x06.Speed\x12\x1b\n\x08velocity\x18\n \x01(\x0b\x32\t.Velocityb\x06proto3'
  ,
  dependencies=[Accelerometer__pb2.DESCRIPTOR,AmbientLight__pb2.DESCRIPTOR,ColorSensor__pb2.DESCRIPTOR,CoreTime__pb2.DESCRIPTOR,Gyroscope__pb2.DESCRIPTOR,IMU__pb2.DESCRIPTOR,Locator__pb2.DESCRIPTOR,Quaternion__pb2.DESCRIPTOR,Speed__pb2.DESCRIPTOR,Velocity__pb2.DESCRIPTOR,])




_SENSORDATAREQUEST = _descriptor.Descriptor(
  name='SensorDataRequest',
  full_name='SensorDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensorFlagLength', full_name='SensorDataRequest.sensorFlagLength', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensorFlag', full_name='SensorDataRequest.sensorFlag', index=1,
      number=2, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=255,
)


_SENSORDATA = _descriptor.Descriptor(
  name='SensorData',
  full_name='SensorData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accelerometer', full_name='SensorData.accelerometer', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ambient_light', full_name='SensorData.ambient_light', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='color_sensor', full_name='SensorData.color_sensor', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='core_time', full_name='SensorData.core_time', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gyroscope', full_name='SensorData.gyroscope', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imu', full_name='SensorData.imu', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='locator', full_name='SensorData.locator', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quaternion', full_name='SensorData.quaternion', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed', full_name='SensorData.speed', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='SensorData.velocity', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=575,
)

_SENSORDATA.fields_by_name['accelerometer'].message_type = Accelerometer__pb2._ACCELEROMETER
_SENSORDATA.fields_by_name['ambient_light'].message_type = AmbientLight__pb2._AMBIENTLIGHT
_SENSORDATA.fields_by_name['color_sensor'].message_type = ColorSensor__pb2._COLORSENSOR
_SENSORDATA.fields_by_name['core_time'].message_type = CoreTime__pb2._CORETIME
_SENSORDATA.fields_by_name['gyroscope'].message_type = Gyroscope__pb2._GYROSCOPE
_SENSORDATA.fields_by_name['imu'].message_type = IMU__pb2._IMU
_SENSORDATA.fields_by_name['locator'].message_type = Locator__pb2._LOCATOR
_SENSORDATA.fields_by_name['quaternion'].message_type = Quaternion__pb2._QUATERNION
_SENSORDATA.fields_by_name['speed'].message_type = Speed__pb2._SPEED
_SENSORDATA.fields_by_name['velocity'].message_type = Velocity__pb2._VELOCITY
DESCRIPTOR.message_types_by_name['SensorDataRequest'] = _SENSORDATAREQUEST
DESCRIPTOR.message_types_by_name['SensorData'] = _SENSORDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorDataRequest = _reflection.GeneratedProtocolMessageType('SensorDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENSORDATAREQUEST,
  '__module__' : 'SensorData_pb2'
  # @@protoc_insertion_point(class_scope:SensorDataRequest)
  })
_sym_db.RegisterMessage(SensorDataRequest)

SensorData = _reflection.GeneratedProtocolMessageType('SensorData', (_message.Message,), {
  'DESCRIPTOR' : _SENSORDATA,
  '__module__' : 'SensorData_pb2'
  # @@protoc_insertion_point(class_scope:SensorData)
  })
_sym_db.RegisterMessage(SensorData)


_SENSORDATAREQUEST.fields_by_name['sensorFlag']._options = None
# @@protoc_insertion_point(module_scope)
